language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "lovedan"
  - git config user.email "xsge@vip.qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --quiet "https://lovedan:${CODING_TOKEN}@${CO_REF}" master:master --tags
   
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/lovedan/hexo-blog.git
   - CO_REF: git@git.dev.tencent.com:lovedan/hexo.git
