language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init 
  - git config user.name "lovedan"
  - git config user.email "xsge@vip.qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://lovedan:${CODING_TOKEN}@${CO_REF}" master:master
   
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/lovedan/hexo-blog.git
   - CO_REF: git.dev.tencent.com/lovedan/hexo.git
